[package]
name = "packetstream"
version = "0.1.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
description = "Secure Scuttlebutt packet stream protocol"
repository = "https://github.com/sunrise-choir/packetstream"
documentation = "https://docs.rs/packetstream/"
readme = "README.md"
keywords = ["packet-stream", "protocol", "ssb", "scuttlebutt"]

[dependencies]
byteorder = "1"
futures-preview = "0.3.0-alpha.13"

[dev-dependencies]
async-ringbuffer = { git = "https://github.com/sbillig/async-ringbuffer", rev = "0eaab49" }
